
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using SimpleJSON;
using Luban;

namespace Editor.cfg
{

public sealed class StringFloat :  Luban.EditorBeanBase 
{
    public StringFloat()
    {
            Item1 = "";
    }

    public override void LoadJson(SimpleJSON.JSONObject _json)
    {
        { 
            var _fieldJson = _json["Item1"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  Item1 = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Item2"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Item2 = _fieldJson;
            }
        }
        
    }

    public override void SaveJson(SimpleJSON.JSONObject _json)
    {
        {

            if (Item1 == null) { throw new System.ArgumentNullException(); }
            _json["Item1"] = new JSONString(Item1);
        }
        {
            _json["Item2"] = new JSONNumber(Item2);
        }
    }

    public static StringFloat LoadJsonStringFloat(SimpleJSON.JSONNode _json)
    {
        StringFloat obj = new StringFloat();
        obj.LoadJson((SimpleJSON.JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonStringFloat(StringFloat _obj, SimpleJSON.JSONNode _json)
    {
        _obj.SaveJson((SimpleJSON.JSONObject)_json);
    }

    public string Item1;

    public float Item2;

}
}

