
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using SimpleJSON;
using Luban;

namespace Editor.cfg
{

public sealed class TableUnit :  Luban.EditorBeanBase 
{
    public TableUnit()
    {
            Name = "";
            ActiveSkill = System.Array.Empty<int>();
            PassiveSkill = System.Array.Empty<int>();
            InitialAttribute = System.Array.Empty<Int2>();
    }

    public override void LoadJson(SimpleJSON.JSONObject _json)
    {
        { 
            var _fieldJson = _json["Id"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Id = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Name"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  Name = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["ActiveSkill"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsArray) { throw new SerializationException(); } int _n0 = _fieldJson.Count; ActiveSkill = new int[_n0]; int _index0=0; foreach(SimpleJSON.JSONNode __e0 in _fieldJson.Children) { int __v0;  if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0;  ActiveSkill[_index0++] = __v0; }  
            }
        }
        
        { 
            var _fieldJson = _json["PassiveSkill"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsArray) { throw new SerializationException(); } int _n0 = _fieldJson.Count; PassiveSkill = new int[_n0]; int _index0=0; foreach(SimpleJSON.JSONNode __e0 in _fieldJson.Children) { int __v0;  if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0;  PassiveSkill[_index0++] = __v0; }  
            }
        }
        
        { 
            var _fieldJson = _json["InitialAttribute"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsArray) { throw new SerializationException(); } int _n0 = _fieldJson.Count; InitialAttribute = new Int2[_n0]; int _index0=0; foreach(SimpleJSON.JSONNode __e0 in _fieldJson.Children) { Int2 __v0;  if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = Int2.LoadJsonInt2(__e0);  InitialAttribute[_index0++] = __v0; }  
            }
        }
        
    }

    public override void SaveJson(SimpleJSON.JSONObject _json)
    {
        {
            _json["Id"] = new JSONNumber(Id);
        }
        {

            if (Name == null) { throw new System.ArgumentNullException(); }
            _json["Name"] = new JSONString(Name);
        }
        {

            if (ActiveSkill == null) { throw new System.ArgumentNullException(); }
            { var __cjson0 = new JSONArray(); _json["ActiveSkill"] = __cjson0; foreach(var _e0 in ActiveSkill) { JSONNode __v0; __v0 = new JSONNumber(_e0); __cjson0.Add(__v0); } }
        }
        {

            if (PassiveSkill == null) { throw new System.ArgumentNullException(); }
            { var __cjson0 = new JSONArray(); _json["PassiveSkill"] = __cjson0; foreach(var _e0 in PassiveSkill) { JSONNode __v0; __v0 = new JSONNumber(_e0); __cjson0.Add(__v0); } }
        }
        {

            if (InitialAttribute == null) { throw new System.ArgumentNullException(); }
            { var __cjson0 = new JSONArray(); _json["InitialAttribute"] = __cjson0; foreach(var _e0 in InitialAttribute) { JSONNode __v0; { var __bjson1 = new JSONObject();  __v0 = __bjson1; Int2.SaveJsonInt2(_e0, __bjson1); } __cjson0.Add(__v0); } }
        }
    }

    public static TableUnit LoadJsonTableUnit(SimpleJSON.JSONNode _json)
    {
        TableUnit obj = new TableUnit();
        obj.LoadJson((SimpleJSON.JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonTableUnit(TableUnit _obj, SimpleJSON.JSONNode _json)
    {
        _obj.SaveJson((SimpleJSON.JSONObject)_json);
    }

    public int Id;

    public string Name;

    /// <summary>
    /// 主动技能
    /// </summary>
    public int[] ActiveSkill;

    /// <summary>
    /// 被动技能
    /// </summary>
    public int[] PassiveSkill;

    /// <summary>
    /// 初始属性
    /// </summary>
    public Int2[] InitialAttribute;

}
}

