
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace cfg
{
public partial class Tables
{
    public TbHero TbHero {get; }
    public TbSkill TbSkill {get; }
    public TbSkillGraph TbSkillGraph {get; }
    public TbUnit TbUnit {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        TbHero = new TbHero(loader("tbhero"));
        TbSkill = new TbSkill(loader("tbskill"));
        TbSkillGraph = new TbSkillGraph(loader("tbskillgraph"));
        TbUnit = new TbUnit(loader("tbunit"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbHero.ResolveRef(this);
        TbSkill.ResolveRef(this);
        TbSkillGraph.ResolveRef(this);
        TbUnit.ResolveRef(this);
    }
}

}
