
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class NodeJson : Luban.BeanBase
{
    public NodeJson(ByteBuf _buf) 
    {
        NodeType = _buf.ReadInt();
        Content = _buf.ReadString();
    }

    public static NodeJson DeserializeNodeJson(ByteBuf _buf)
    {
        return new NodeJson(_buf);
    }

    public readonly int NodeType;
    public readonly string Content;
   
    public const int __ID__ = 1187422762;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "nodeType:" + NodeType + ","
        + "content:" + Content + ","
        + "}";
    }
}
}

