
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class TableSkillGraph : Luban.BeanBase
{
    public TableSkillGraph(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        SkillId = _buf.ReadString();
        Name = _buf.ReadString();
        Description = _buf.ReadString();
        {int n0 = _buf.ReadSize(); NodesJsons = new System.Collections.Generic.List<NodeJson>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { NodeJson _e0;  _e0 = global::cfg.NodeJson.DeserializeNodeJson(_buf); NodesJsons.Add(_e0);}}
        {int n0 = _buf.ReadSize(); ConnectionsJson = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); ConnectionsJson.Add(_e0);}}
    }

    public static TableSkillGraph DeserializeTableSkillGraph(ByteBuf _buf)
    {
        return new TableSkillGraph(_buf);
    }

    /// <summary>
    /// 主键ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 技能标识
    /// </summary>
    public readonly string SkillId;
    /// <summary>
    /// 技能名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 技能描述
    /// </summary>
    public readonly string Description;
    /// <summary>
    /// 节点数据JSON
    /// </summary>
    public readonly System.Collections.Generic.List<NodeJson> NodesJsons;
    /// <summary>
    /// 连接数据JSON
    /// </summary>
    public readonly System.Collections.Generic.List<string> ConnectionsJson;
   
    public const int __ID__ = 833402827;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in NodesJsons) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "SkillId:" + SkillId + ","
        + "Name:" + Name + ","
        + "Description:" + Description + ","
        + "NodesJsons:" + Luban.StringUtil.CollectionToString(NodesJsons) + ","
        + "ConnectionsJson:" + Luban.StringUtil.CollectionToString(ConnectionsJson) + ","
        + "}";
    }
}
}

