
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbSkillGraph
{
    private readonly System.Collections.Generic.Dictionary<int, TableSkillGraph> _dataMap;
    private readonly System.Collections.Generic.List<TableSkillGraph> _dataList;
    
    public TbSkillGraph(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, TableSkillGraph>(n);
        _dataList = new System.Collections.Generic.List<TableSkillGraph>(n);
        for(int i = n ; i > 0 ; --i)
        {
            TableSkillGraph _v;
            _v = global::cfg.TableSkillGraph.DeserializeTableSkillGraph(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, TableSkillGraph> DataMap => _dataMap;
    public System.Collections.Generic.List<TableSkillGraph> DataList => _dataList;

    public TableSkillGraph GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public TableSkillGraph Get(int key) => _dataMap[key];
    public TableSkillGraph this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

