
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using SimpleJSON;
using Luban;

namespace Editor.cfg
{

public sealed class Float2 :  Luban.EditorBeanBase 
{
    public Float2()
    {
    }

    public override void LoadJson(SimpleJSON.JSONObject _json)
    {
        { 
            var _fieldJson = _json["Item1"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Item1 = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Item2"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Item2 = _fieldJson;
            }
        }
        
    }

    public override void SaveJson(SimpleJSON.JSONObject _json)
    {
        {
            _json["Item1"] = new JSONNumber(Item1);
        }
        {
            _json["Item2"] = new JSONNumber(Item2);
        }
    }

    public static Float2 LoadJsonFloat2(SimpleJSON.JSONNode _json)
    {
        Float2 obj = new Float2();
        obj.LoadJson((SimpleJSON.JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonFloat2(Float2 _obj, SimpleJSON.JSONNode _json)
    {
        _obj.SaveJson((SimpleJSON.JSONObject)_json);
    }

    public float Item1;

    public float Item2;

}
}

