
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using SimpleJSON;
using Luban;

namespace Editor.cfg
{

public sealed class Int4 :  Luban.EditorBeanBase 
{
    public Int4()
    {
    }

    public override void LoadJson(SimpleJSON.JSONObject _json)
    {
        { 
            var _fieldJson = _json["Item1"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Item1 = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Item2"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Item2 = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Item3"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Item3 = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Item4"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Item4 = _fieldJson;
            }
        }
        
    }

    public override void SaveJson(SimpleJSON.JSONObject _json)
    {
        {
            _json["Item1"] = new JSONNumber(Item1);
        }
        {
            _json["Item2"] = new JSONNumber(Item2);
        }
        {
            _json["Item3"] = new JSONNumber(Item3);
        }
        {
            _json["Item4"] = new JSONNumber(Item4);
        }
    }

    public static Int4 LoadJsonInt4(SimpleJSON.JSONNode _json)
    {
        Int4 obj = new Int4();
        obj.LoadJson((SimpleJSON.JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonInt4(Int4 _obj, SimpleJSON.JSONNode _json)
    {
        _obj.SaveJson((SimpleJSON.JSONObject)_json);
    }

    public int Item1;

    public int Item2;

    public int Item3;

    public int Item4;

}
}

