
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using SimpleJSON;
using Luban;

namespace Editor.cfg
{

public sealed class TableSkillGraph :  Luban.EditorBeanBase 
{
    public TableSkillGraph()
    {
            Name = "";
            Description = "";
            NodesJsons = new System.Collections.Generic.List<NodeJson>();
            ConnectionsJson = new System.Collections.Generic.List<string>();
    }

    public override void LoadJson(SimpleJSON.JSONObject _json)
    {
        { 
            var _fieldJson = _json["Id"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Id = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Name"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  Name = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Description"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  Description = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["NodesJsons"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsArray) { throw new SerializationException(); } NodesJsons = new System.Collections.Generic.List<NodeJson>(); foreach(JSONNode __e0 in _fieldJson.Children) { NodeJson __v0;  if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = NodeJson.LoadJsonNodeJson(__e0);  NodesJsons.Add(__v0); }  
            }
        }
        
        { 
            var _fieldJson = _json["ConnectionsJson"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsArray) { throw new SerializationException(); } ConnectionsJson = new System.Collections.Generic.List<string>(); foreach(JSONNode __e0 in _fieldJson.Children) { string __v0;  if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0;  ConnectionsJson.Add(__v0); }  
            }
        }
        
    }

    public override void SaveJson(SimpleJSON.JSONObject _json)
    {
        {
            _json["Id"] = new JSONNumber(Id);
        }
        {

            if (Name == null) { throw new System.ArgumentNullException(); }
            _json["Name"] = new JSONString(Name);
        }
        {

            if (Description == null) { throw new System.ArgumentNullException(); }
            _json["Description"] = new JSONString(Description);
        }
        {

            if (NodesJsons == null) { throw new System.ArgumentNullException(); }
            { var __cjson0 = new JSONArray(); _json["NodesJsons"] = __cjson0; foreach(var _e0 in NodesJsons) { JSONNode __v0; { var __bjson1 = new JSONObject();  __v0 = __bjson1; NodeJson.SaveJsonNodeJson(_e0, __bjson1); } __cjson0.Add(__v0); } }
        }
        {

            if (ConnectionsJson == null) { throw new System.ArgumentNullException(); }
            { var __cjson0 = new JSONArray(); _json["ConnectionsJson"] = __cjson0; foreach(var _e0 in ConnectionsJson) { JSONNode __v0; __v0 = new JSONString(_e0); __cjson0.Add(__v0); } }
        }
    }

    public static TableSkillGraph LoadJsonTableSkillGraph(SimpleJSON.JSONNode _json)
    {
        TableSkillGraph obj = new TableSkillGraph();
        obj.LoadJson((SimpleJSON.JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonTableSkillGraph(TableSkillGraph _obj, SimpleJSON.JSONNode _json)
    {
        _obj.SaveJson((SimpleJSON.JSONObject)_json);
    }

    /// <summary>
    /// 主键ID
    /// </summary>
    public int Id;

    /// <summary>
    /// 技能名称
    /// </summary>
    public string Name;

    /// <summary>
    /// 技能描述
    /// </summary>
    public string Description;

    /// <summary>
    /// 节点数据JSON
    /// </summary>
    public System.Collections.Generic.List<NodeJson> NodesJsons;

    /// <summary>
    /// 连接数据JSON
    /// </summary>
    public System.Collections.Generic.List<string> ConnectionsJson;

}
}

